version: "3.5"

services:
  redis:
    image: redis:6-alpine
    ports:
      - 0.0.0.0:6379:6379
  web:
    image: nginx
    #ports:
    #  - 127.0.0.1:3005:3000
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  
  
networks:
  rawstore: 
